contactList/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'contactList'
urlpatterns = [
	#ex: /contactList/
    path('', views.ContactCreate.as_view(), name='index'),
    path('contacts/', views.ContactList.as_view(), name='contacts'),
    path('mailer/', views.ContactCreate.as_view(), name='contact_create'),
    path('update/<int:pk>', views.ContactUpdate.as_view(), name='contact_update'),
    path('delete/<int:pk>', views.ContactDelete.as_view(), name='contact_delete'),
    path('thanks/', views.thanks, name='thanks'),
    path('login/', auth_views.LoginView.as_view(template_name='contactList/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='contactList/logout.html', next_page ='contactList:contact_create'), name='logout'),
]

projectSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('contactList/', include('contactList.urls')),
    path('admin/', admin.site.urls),
]

contactList/models.py
from django.db import models
import json
import urllib.parse
from decimal import Decimal

from .config import MapBoxConfig

class Contact(models.Model):

    def save(self):
        address = "%s %s, %s %s" % (self.street, self.city, self.state, self.zip)
        self.latitude,self.longitude = self.geocode(address)
        super(Contact, self).save()

    def geocode(self, address):
        address = urllib.parse.quote_plus(address)
        maps_api_url = '?'.join([
            'https://api.mapbox.com/geocoding/v5/mapbox.places/' + address + '.json',
            urllib.parse.urlencode({'access_token': MapBoxConfig.access_token, 'autocomplete':True})
        ])
        response = urllib.request.urlopen(maps_api_url)
        data = json.loads(response.read().decode('utf8'))
        if 'features' in data:
            longitude = data['features'][0]['geometry']['coordinates'][0]
            latitude = data['features'][0]['geometry']['coordinates'][1]
            return Decimal(latitude),Decimal(longitude)
        else:
            return None, None

    NJ = 'NJ'
    NY = 'NY'
    PA = 'PA'
    CT = 'CT'
    STATE_CHOICES = (
        (NJ, 'New Jersey'),
        (NY, 'New York'),
        (PA, 'Pennsylvania'),
        (CT, 'Connecticut'),
    )
    MR = 'Mr.'
    MS = 'Ms.'
    MRS = 'Mrs.'
    DR = 'Dr.'
    TITLE_CHOICES = (
        (MR,MR),
        (MS,MS),
        (MRS,MRS),
        (DR,DR),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=100)
    state = models.CharField(
        max_length=20,
        choices = STATE_CHOICES,
        default = NJ,
    )
    zip = models.CharField(max_length=5)
    phone = models.CharField(max_length=12)
    email = models.CharField(max_length=50)
    title = models.CharField(
        max_length=5,
        choices = TITLE_CHOICES,
        default = MR,
    )
    use_mail = models.BooleanField()
    use_phone = models.BooleanField()
    use_email = models.BooleanField()
    latitude = models.DecimalField(max_digits=8, decimal_places=5,null=True,editable=False)
    longitude = models.DecimalField(max_digits=8, decimal_places=5,null=True,editable=False)

contactList/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Contact
from .config import MapBoxConfig

class ContactList(LoginRequiredMixin,generic.ListView):
    login_url = 'contactList:login'
    template_name = 'contactList/contact_list.html'
    context_object_name = 'contact_list'

    def get_queryset(self):
        return Contact.objects.order_by('last_name'),MapBoxConfig.access_token

def thanks(request):
    return render(request, 'contactList/thanks.html')

class ContactCreate(generic.edit.CreateView):
    model = Contact
    success_url = '../thanks/'
    fields = '__all__'

class ContactUpdate(generic.edit.UpdateView):
    model = Contact
    success_url = '../'
    fields = '__all__'

class ContactDelete(generic.edit.DeleteView):
    model = Contact
    success_url = '../'

contactList/templates/contactList/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
    <style>
      #tr.point{
          cursor:pointer;
        }
        #map {
          height: 100%;
          width: 100%;
        }
        #map-canvas {
      		position: absolute;
			    margin-top:5px;
          padding-bottom: 30px;
          width:50%;
			    height:85%;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
 		<div class="container-fluid">
	 		<div class="navbar-header">
		 		<a class="navbar-brand" href="{% url 'contactList:index' %}">Marketing</a>
	 		</div>
	 	<div>
		 <ul class="nav navbar-nav">
			 <li class="active"><a href="{% url 'contactList:index' %}">Contact Form</a></li>
			 <li><a href="{% url 'contactList:contacts' %}">Contacts Table</a></li>
		 </ul>
		 <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a href="#"><span class="glyphicon glyphicon-check"></span> Logged In as {{ user.username }}</a></li>
          <li><a href="{% url 'contactList:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
					<li><a href="{% url 'contactList:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
	 </div>
 </div>
</nav>
  <div class= 'container'>
    {% block content %}
    {% endblock %}
  </div>
  </body>
</html>

contactList/templates/contactList/contact_confirm_delete.html
{% extends 'contactList/base.html' %}

{% block title %}Contact Information Delete{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.title }} {{ object.first_name }} {{ object.last_name }}?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'contactList:contacts' %}"><input type="button" value="Back"></a>
</form>
{% endblock %}

contactList/templates/contactList/contact_form.html
{% extends 'contactList/base.html' %}

{% block title %}Contact Information Form{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

contactList/templates/contactList/contact_list.html
{% extends 'contactList/base.html' %}

{% block title %}Contact Information Table{% endblock %}

{% block content %}
      {% if contact_list.0 %}
        <h1>Table of Contacts</h1>
        <a href="{% url 'contactList:contact_create' %}"><button class ='btn btn-success'>Make Contact</button></a>
        <div class='table-responsive'>
          <table class="table table-hover">
            <tr>
              <th>Last Name</th>
              <th>First Name</th>
              <th>Street Address</th>
              <th>City</th>
              <th>State</th>
              <th>Zip Code</th>
              <th>Phone Number</th>
              <th>Email</th>
              <th>Title</th>
              <th>Contact by Phone</th>
              <th>Contact by Mail</th>
              <th>Contact by Email</th>
            </tr>
            {% for contact in contact_list.0 %}
              <tr class='point' id= {{ contact.id }} data-pos=[{{ contact.longitude }},{{ contact.latitude }}]>
                <td>{{ contact.last_name }}</td>
                <td>{{ contact.first_name }}</td>
                <td>{{ contact.street }}</td>
                <td>{{ contact.city }}</td>
                <td>{{ contact.state }}</td>
                <td>{{ contact.zip }}</td>
                <td>{{ contact.phone }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.title }}</td>
                <td>{{ contact.use_mail }}</td>
                <td>{{ contact.use_phone }}</td>
                <td>{{ contact.use_email }}</td>
                <td><a href="{% url 'contactList:contact_update' contact.id %}"><button type= 'button' class ='btn btn-info'>Edit</button></a></td>
                <td><a href="{% url 'contactList:contact_delete' contact.id %}"><button type= 'button' class ='btn btn-warning'>Delete</button></a></td>
              </tr>
            {% endfor %}
          </table>
        </div>
        <div id="map-canvas"><div id="map"></div></div>
      {% else %}
        <p>No contacts.</p>
      {% endif %}
  <script>
    mapboxgl.accessToken = '{{contact_list.1}}';
    var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v9', // stylesheet location
      center: [-74.176609, 41.08394699999999], // starting position [lng, lat]
      zoom: 8 // starting zoom
    });


    //On map load
    map.on('load', function() {
      var features = [];
      $('tr.point').each(function() {
        var pos = $(this).data('pos');
        var label = "<strong>" + $(this).children().slice(8,9).text() + " "
             + $(this).children().slice(1,2).text() + " "
             + $(this).children().slice(0,1).text() + "</strong><br/>"
             + $(this).children().slice(2,3).text() + "<br/>"
             + $(this).children().slice(3,4).text() + ", "
             + $(this).children().slice(4,5).text() + " "
             + $(this).children().slice(5,6).text() + "<br/>"
        features.push({
            "type": "Feature",
            "properties": {"description":label},
            "geometry": {
              "type": "Point",
              "coordinates": pos
            }
        })
      });
      // Add a layer showing the places.
      map.addLayer({
        "id": "places",
        "type": "symbol",
        "source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": features
          }
        },
          "layout": {
          "icon-image": "circle-stroked-15",
          "icon-allow-overlap": true
        }
      });

      // Create a popup, but don't add it to the map yet.
      var popup = new mapboxgl.Popup({
        closeButton: false,
        closeOnClick: false
      });

      map.on('mouseenter', 'places', function(e) {
        // Change the cursor style as a UI indicator.
        map.getCanvas().style.cursor = 'pointer';

        var coordinates = e.features[0].geometry.coordinates.slice();
        var description = e.features[0].properties.description;

        // Ensure that if the map is zoomed out such that multiple
        // copies of the feature are visible, the popup appears
        // over the copy being pointed to.
        while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
          coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
        }

        // Populate the popup and set its coordinates
        // based on the feature found.
        popup.setLngLat(coordinates)
          .setHTML(description)
          .addTo(map);
        });

        map.on('mouseleave', 'places', function() {
          map.getCanvas().style.cursor = '';
          popup.remove();
        });
    });
  </script>
{% endblock %}

contactList/templates/contactList/contact_update_form.html
{% extends 'contactList/base.html' %}

{% block title %}Contact Information Form{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

contactList/templates/contactList/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <title>Contact Information Table</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
    <style>
      #tr.point{
          cursor:pointer;
        }
        #map {
          height: 100%;
          width: 100%;
        }
        #map-canvas {
      		position: absolute;
			    margin-top:5px;
          padding-bottom: 30px;
          width:50%;
			    height:85%;
        }
    </style>
  </head>
  <body>
    <div class='container'>
      {% if contact_list.0 %}
        <h1>Table of Contacts</h1>
        <a href="{% url 'contactList:contact_create' %}"><button class ='btn btn-success'>Make Contact</button></a>
        <div class='table-responsive'>
          <table class="table table-hover">
            <tr>
              <th>Last Name</th>
              <th>First Name</th>
              <th>Street Address</th>
              <th>City</th>
              <th>State</th>
              <th>Zip Code</th>
              <th>Phone Number</th>
              <th>Email</th>
              <th>Title</th>
              <th>Contact by Phone</th>
              <th>Contact by Mail</th>
              <th>Contact by Email</th>
            </tr>
            {% for contact in contact_list.0 %}
              <tr class='point' id= {{ contact.id }} data-pos=[{{ contact.longitude }},{{ contact.latitude }}]>
                <td>{{ contact.last_name }}</td>
                <td>{{ contact.first_name }}</td>
                <td>{{ contact.street }}</td>
                <td>{{ contact.city }}</td>
                <td>{{ contact.state }}</td>
                <td>{{ contact.zip }}</td>
                <td>{{ contact.phone }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.title }}</td>
                <td>{{ contact.use_mail }}</td>
                <td>{{ contact.use_phone }}</td>
                <td>{{ contact.use_email }}</td>
                <td><a href="{% url 'contactList:contact_update' contact.id %}"><button type= 'button' class ='btn btn-info'>Edit</button></a></td>
                <td><a href="{% url 'contactList:contact_delete' contact.id %}"><button type= 'button' class ='btn btn-warning'>Delete</button></a></td>
              </tr>
            {% endfor %}
          </table>
        </div>
        <div id="map-canvas"><div id="map"></div></div>
      {% else %}
        <p>No contacts.</p>
      {% endif %}
    </div>
  </body>
  <script>
    mapboxgl.accessToken = '{{contact_list.1}}';
    var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v9', // stylesheet location
      center: [-74.176609, 41.08394699999999], // starting position [lng, lat]
      zoom: 8 // starting zoom
    });


    //On map load
    map.on('load', function() {
      var features = [];
      $('tr.point').each(function() {
        var pos = $(this).data('pos');
        var label = "<strong>" + $(this).children().slice(8,9).text() + " "
             + $(this).children().slice(1,2).text() + " "
             + $(this).children().slice(0,1).text() + "</strong><br/>"
             + $(this).children().slice(2,3).text() + "<br/>"
             + $(this).children().slice(3,4).text() + ", "
             + $(this).children().slice(4,5).text() + " "
             + $(this).children().slice(5,6).text() + "<br/>"
        features.push({
            "type": "Feature",
            "properties": {"description":label},
            "geometry": {
              "type": "Point",
              "coordinates": pos
            }
        })
      });
      // Add a layer showing the places.
      map.addLayer({
        "id": "places",
        "type": "symbol",
        "source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": features
          }
        },
          "layout": {
          "icon-image": "circle-stroked-15",
          "icon-allow-overlap": true
        }
      });

      // Create a popup, but don't add it to the map yet.
      var popup = new mapboxgl.Popup({
        closeButton: false,
        closeOnClick: false
      });

      map.on('mouseenter', 'places', function(e) {
        // Change the cursor style as a UI indicator.
        map.getCanvas().style.cursor = 'pointer';

        var coordinates = e.features[0].geometry.coordinates.slice();
        var description = e.features[0].properties.description;

        // Ensure that if the map is zoomed out such that multiple
        // copies of the feature are visible, the popup appears
        // over the copy being pointed to.
        while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
          coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
        }

        // Populate the popup and set its coordinates
        // based on the feature found.
        popup.setLngLat(coordinates)
          .setHTML(description)
          .addTo(map);
        });

        map.on('mouseleave', 'places', function() {
          map.getCanvas().style.cursor = '';
          popup.remove();
        });
    });
  </script>
</html>

contactList/templates/contactList/login.html
{% extends 'contactList/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}

  {% if form.errors %}
    <div class="alert alert-danger"><p>Your username and password didn't match. Please try again.</p></div>
  {% endif %}

  {% if next %}
      {% if user.is_authenticated %}
        <div class="alert alert-warning"><p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p></div>
      {% else %}
        <div class="alert alert-warning"><p>Please login to see this page.</p></div>
      {% endif %}
  {% endif %}
  <h2>Log In</h2>
<form method="post" action="{% url 'contactList:login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>

  <input type="submit" value="login">
  <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

contactList/templates/contactList/logout.html
{% extends 'base.html' %}

{% block title %}Logged Out{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'contactList:login' %}">Log in</a> again.</p>
{% endblock %}

contactList/templates/contactList/thanks.html
{% extends 'contactList/base.html' %}

{% block title %}Thanks!{% endblock %}

{% block content %}
    <h1>Thank you for your information!</h1>
    <p><a href = "{% url 'contactList:contact_create' %}">Return to input page</a></p>
{% endblock %}